### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by VanHoevenTR** [Octowolve/Hooking-Template-With-Mod-Menu#14]
Hello
I made this menu first since 2019, before I left modding, https://platinmods.com/threads/template-menu-free-for-mod-menu-il2cpp-and-other-native-games.67429/
by looking though your first commits, I can see it was based on mine.
No offense, just saying if you can credit to me :)

**Comment by Octowolve** [comment]
No it isn't. Just take a look at the commit date.

**Comment by VanHoevenTR** [comment]
Yes it is, you changed everything to hide. You didn't credit to MrIkso either
