### ISSUE TITLE
Possible bug when stopping the mod menu

### ISSUE THREAD

**Issue by ghost** [Octowolve/Hooking-Template-With-Mod-Menu#7]
In [MenuService onDestroy](https://github.com/z3r0Sec/Substrate-Template-With-Mod-Menu/blob/ec8c40ca20cbf79ce529a4eef35d7abc9e2f8147/app/src/main/java/com/dark/force/MenuService.java#L77):
```
windowManager.removeView(imageView);
```

but imageView is never added to windowManager so the app crash when the "kill" button is pressed.

**Comment by Octowolve** [comment]
Oh damn I didnt remove it here. thanks for the info
